import dayjs from 'dayjs/esm';

import { IFormBASTPBP, NewFormBASTPBP } from './form-bastpbp.model';

export const sampleWithRequiredData: IFormBASTPBP = {
  id: '7d167fef-3c3e-4077-94b9-ce5cce56dbb8',
  active: true,
  createdDate: dayjs('2023-04-17T16:17'),
};

export const sampleWithPartialData: IFormBASTPBP = {
  id: 'c098074a-44c4-4af6-af21-a3ad2a3367a3',
  status: 'Lo',
  active: false,
  remarks: 'Cyprus',
  documentTitle: 'RSS Developer static',
  documentNumber: 'Zealand Comoros',
  kelurahanDesa: 'vortals',
  kcu: 'interactive Soap',
  jumlah1: 'com',
  alamat2: 'Practical online Rico',
  nomor2: 'purple',
  alamat3: 'contextually-based',
  nomor3: 'Strategist Loti Table',
  jumlah3: 'env',
  nama4: 'Fresh tan',
  alamat4: 'deliver',
  jumlah4: 'dep',
  nama5: 'generation',
  nomor5: 'killer distributed Small',
  nama6: 'Chief',
  nama7: 'Rubber Account',
  alamat7: 'Electronics directional Card',
  nomor7: 'Division e-markets',
  jumlah7: 'up',
  nama8: 'systems PCI backing',
  nama10: 'Auto',
  alamat10: 'input transmitter 4th',
  nomor10: 'Fundamental program blue',
  jumlah10: 'Woo',
  nomor6: 'Accountability',
  jumlah6: 'sca',
  createdDate: dayjs('2023-04-18T00:07'),
  lastModifiedBy: 'Plastic Soap',
};

export const sampleWithFullData: IFormBASTPBP = {
  id: '2111e908-4c24-41ef-835e-fb0e82ee451f',
  status: 'co',
  active: false,
  remarks: 'Riel Licensed Democratic',
  contents: 'panel',
  documentTitle: 'paradigms Handcrafted',
  documentNumber: 'SCSI',
  kelurahanDesa: 'Industrial New Home',
  kecamatan: 'distributed bandwidth',
  kabupatenKota: 'Executive Loan',
  provinsi: 'deposit Refined Sol',
  rtRw: 'indexing m',
  kcu: 'Global benchmark Saint',
  kantorSerah: 'Libyan',
  bastNumber: 'XSS River Outdoors',
  documentDescription: 'explicit withdrawal',
  nama1: 'bus Future Pre-emptive',
  alamat1: 'User-friendly',
  nomor1: 'Liaison',
  jumlah1: 'vio',
  nama2: 'invoice',
  alamat2: 'deposit French Gorgeous',
  nomor2: 'Research intuitive Maryland',
  jumlah2: 'Re-',
  nama3: 'Sudan Wooden pixel',
  alamat3: 'Buckinghamshire Consultant Creative',
  nomor3: 'optimal SAS',
  jumlah3: 'ver',
  nama4: 'Architect pixel',
  alamat4: 'National Directives Tools',
  nomor4: 'Clothing',
  jumlah4: 'blu',
  nama5: 'Franc FTP connecting',
  alamat5: 'generating transmitting Louisiana',
  nomor5: 'Cross-group indexing Borders',
  jumlah5: 'Tas',
  nama6: 'Salad Wooden',
  nama7: 'Guernsey Mobility',
  alamat7: 'Tasty',
  nomor7: 'Bedfordshire impactful Mandatory',
  jumlah7: 'Tra',
  nama8: 'Maine',
  alamat8: 'Account',
  nomor8: 'Money',
  jumlah8: 'Chi',
  nama9: 'Frozen',
  alamat9: 'deliver',
  nomor9: 'invoice dynamic CSS',
  jumlah9: 'bac',
  nama10: 'Ergonomic',
  alamat10: 'Shoes Small',
  nomor10: 'hierarchy Pennsylvania Engineer',
  jumlah10: 'Mea',
  alamat6: 'North Functionality holistic',
  nomor6: 'Architect capacity',
  jumlah6: 'Gen',
  createdDate: dayjs('2023-04-17T18:29'),
  createdBy: 'SCSI capacitor',
  lastModifiedDate: dayjs('2023-04-18T03:01'),
  lastModifiedBy: 'regional Interface',
};

export const sampleWithNewData: NewFormBASTPBP = {
  active: true,
  createdDate: dayjs('2023-04-17T20:25'),
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
